export default function Blog() {
  return (
    <>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
    </>
  );
}
