export default function Blog() {
  return (
    <section id='blog' className='pt-20'>
      <h1 className='text-lg text-purple-400 pb-1'>Blog</h1>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
      <p>BLOGGGGGGGgggGGGgGGGGGGGGGGGGGGGGGG</p>
    </section>
  );
}
